# Generated by Django 4.2.14 on 2024-08-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='test',
            new_name='text',
        ),
    ]
