# Generated by Django 4.2.14 on 2024-08-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_shoppingcart_delete_shoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=22, null=True, unique=True),
        ),
    ]
