# Generated by Django 4.2.14 on 2024-08-07 07:49

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Юзернейм содержит недопустимые символы', regex='^[\\w.@+-]+\\Z'), users.validators.username_not_me], verbose_name='Имя пользователя'),
        ),
    ]
