# Generated by Django 4.2.14 on 2024-08-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Subscribe',
        ),
    ]
